### PR TITLE
Fixed some minor commands(tested)

### PR DESCRIPTION
**Pull request by ksatyarth2**

### CODE REVIEW

**Comment by mzfr** [comment]
@ksatyarth2 why did you removed that `sudo` from requirements installing command?

**Comment by ksatyarth2** [comment]
@mzfr I tried with sudo, but it showed error. After removing sudo, it worked.

**Comment by mzfr** [comment]
@ksatyarth2 Can you please show me the error. I'm asking that because I think without sudo there would be `permission denied` error since we are not having venv command.

**Comment by ksatyarth2** [comment]
error: 
`sudo: pip3.6: command not found`

**Comment by mzfr** [comment]
@ksatyarth2 that is not because of `sudo`, that pip version is not found. Removing sudo would result in permission denied error for people not using the virtual environment. 

I would recommend to not remove that `sudo` from that command.

**Comment by ksatyarth2** [comment]
But after removing `sudo`, the command worked for me and the requirements were installed.

**Comment by mzfr** [comment]
See either you must be in sone virtual environment or you must have done something else maybe you are a root user on the system whatever the reason might be but AFAIK installing pip dependencies without `--user` flag and without being `sudo` will result in `permission denied error`.

Either you have to use `sudo` or you'll have to use `--user` flag. 

But if you think this is the correct way then let's just wait for @blabla1337 to review the changes.

**Comment by ksatyarth2** [comment]
Yes I'm also aware of that and maybe I'm wrong in this case but it doesn't work for me. So, that's why I removed `sudo`.

**Comment by blabla1337** [comment]
@ksatyarth2 I think we need to have the sudo, in my case I also needed it on an Ubuntu installation

**Pull request closed without merging**
