### PR TITLE
Syntax Highlighting

### PR DESCRIPTION
**Pull request by rossnanop**
- Enable syntax highlighting for code examples
- Implement for asp and java
- Fix some typos in asp

### CODE REVIEW

**Comment by RiieCco** [comment]
Hey Ross,

Super awesome, we will look into it right away!
As soon as the SKF project has accepted your pull request you will also be
mentioned as contributer
on the owasp and skf pages!

Again, thank you very much for your contribution!

With kind regards,
Riccardo ten Cate

2016-05-30 4:42 GMT+02:00 Ross Nanopoulos <notifications@github.com>:

**Comment by rossnanop** [comment]
Awesome thanks! If you think it should be done differently let me know.  Another idea I had was integrating directly with githubs markdown api so writing examples feels more natural to writing Github documentation, but that would require more work on the operational side to generate API keys, etc.

**Comment by RiieCco** [comment]
Hey Ross,

As we speak we are merging your Pull requests, thanks again for all the
hard work you put
into SKF. Can you give me your credentials as you would like to see them on
the wiki pages as
contributor? Such as linkedin Account, Email etc

Cheers!

2016-05-30 21:09 GMT+02:00 Ross Nanopoulos <notifications@github.com>:

**Comment by rossnanop** [comment]
For the Github page, you can use my Twitter: [Ross Nanopoulos](https://twitter.com/rossnanop)
LinkedIn is here: https://www.linkedin.com/in/rossnanop

Thanks!

**Comment by adamnfish** [comment]
Thanks heaps for your really helpful contribution! I rebased your work to resolve the merge conflicts so it isn't appearing as "merged" even though your changes are now included. I'll close this PR, but your changes are now part of this project.

I've opened a Pull Request that adds you to the contributors section of the README. Let me know/comment the PR if you'd like to appear under a different alias?
https://github.com/blabla1337/skf-flask/pull/124

**Pull request closed without merging**
